packages:
  - name: coinmate
    actions:
      - name: buy 
        runtime: nodejs:default
      - name: balances
        runtime: nodejs:default
environment:
  PRIVATE_KEY: ${PRIVATE_KEY}
  PUBLIC_KEY: ${PUBLIC_KEY}
  CLIENT_ID: ${CLIENT_ID}
  SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
  API_BASE_URL: ${API_BASE_URL}

